image: atlassian/default-image:3

image: atlassian/default-image:3
pipelines:
  branches:
    master:
      stages:
        - stage: deploy
          when: manual
          steps:
            - step:
                script:
                  - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
                  - ssh -i ~/.ssh/id_rsa /vivikola.ch/stage.app.vivikola.ch
                  - rsync -avz --delete ./vivikola.ch:/vivikola.ch/stage.app.vivikola.ch
