image: atlassian/default-image:3

pipelines:
  branches:
   master:
    stages:
      -stage: deploy
        steps:
        - step:
            name: Deploy to test
            script:
              - echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
              - chmod 600 ~/.ssh/id_rsa
              - ssh -i ~/.ssh/id_rsa /vivikola.ch/stage.app.vivikola.ch
              - rsync -avz --delete ./vivikola.ch/stage.app.vivikola.ch
              # Add any additional deployment commands for the production server
              
