image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: Deploy to test
          deployment: test
          script:
            - apt-get update && apt-get install -y openssh-client
            - echo "$SSH_PRIVATE_KEY1" | base64 -d > ~/.ssh/id_rsa_demotest.pem
            - chmod 600 ~/.ssh/id_rsa_demotest.pem
            - ssh -i ~/.ssh/id_rsa_demotest.pem ss4ucrmc@demotest.ss4ucrm.com "cd /home/ss4ucrmc/demotest.ss4ucrm.com && git pull"
            # Add any additional deployment commands for the production server
